spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /static/
      suffix: .html
server:
  port: 8888


#zk地址信息
zookeeper:
  hosts:
    url: localhost:2181

#task 监控根节点
libra:
  monitor:
    namespace: /libra/root


